name: Pull Request
on: [pull_request] #trigger
jobs:
  PullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Make a new envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_POSTGRES_USER: "postgres"
          envkey_POSTGRES_PASSWORD: "postgres"
          envkey_POSTGRES_DB: "CDCIGitTestes"
          envkey_DATABASE_URL: "DATABASE_URL = postgres://postgres:postgres@db_postgres_git_actions:5432/CDCIGitTestes"
          file_name: ".env.test"
      - name: Run tests
        run: docker-compose -f docker-compose-tests.yml run node_app_git_actions npm run test